name: VeillePurple
options:
  bundleIdPrefix: com.veille
  deploymentTarget:
    iOS: "16.0"
  developmentLanguage: fr
  xcodeVersion: "15.4"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    ENABLE_BITCODE: NO
    SUPPORTS_MACCATALYST: NO
targets:
  VeillePurple:
    type: application
    platform: iOS
    sources:
      - path: VeillePurple
        excludes:
          - "Info.plist"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.veille.purple
        PRODUCT_NAME: VeillePurple
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_IDENTITY: ""
        CODE_SIGN_STYLE: Manual
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
        INFOPLIST_FILE: VeillePurple/Info.plist
        TARGETED_DEVICE_FAMILY: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
        GENERATE_INFOPLIST_FILE: NO
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"